---
name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up env
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "PLATFORM=linux" >> $GITHUB_ENV
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install node dependencies
        run: npm ci
      - name: Install bsdtar
        run: apt install libarchive-tools
      - name: Build Linux
        run: ./scripts/build.sh
      - name: Linux Release
        run: ./scripts/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
